server:
  port: 8980

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          url: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
          username:
          password:
      lable: master
